import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="p-5 bg-primary text-white text-center">
          <h1>Book Management System</h1>
          <h2>React Demo App</h2>
        </header>
        <main className="container mt-5">{children}</main>
        <footer className="mt-5 p-4 bg-dark text-white text-center">
          <p>copyrights &copy; Nithesh 2026</p>
        </footer>
      </body>
    </html>
  );
} 